from pathlib import Path
import pytest
import psycopg
from pytest_postgresql import factories
from testcontainers.postgres import PostgresContainer

# 1. Start the Docker Container (Runs once per test session)
@pytest.fixture(scope="session")
def postgres_container():
    # We explicitly use the pgvector image so the extension is available!
    with PostgresContainer("pgvector/pgvector:pg16") as postgres:
        yield postgres

# This creates a fixture that starts a temporary DB
# You can specify the 'host', 'user', etc., if they differ from defaults
schema_location = Path(__file__).parents[2].joinpath("database", "sql", "init.sql")
test_data = Path(__file__).parent.joinpath("test_data.sql")

@pytest.fixture(scope="session")
def db_session(postgres_container):
    """
    Initializes the schema and provides a psycopg connection.
    """
    # Extract the connection details generated by Docker
    host = postgres_container.get_container_host_ip()
    port = postgres_container.get_exposed_port(5432)
    user = postgres_container.username
    password = postgres_container.password
    dbname = postgres_container.dbname
    # Connection string provided by pytest-postgres
    conn_dict = {
        "host": host,
        "port": port,
        "user": user,
        "password": password,
        "dbname": dbname,
    }
    
    conn_str = f"host={conn_dict['host']} port={conn_dict['port']} dbname={conn_dict['dbname']} user={conn_dict['user']} password={conn_dict['password']}"

    with psycopg.connect(conn_str) as conn:
        with conn.cursor() as cur:
            # Read and execute your schema.sql
            with schema_location.open() as f:
                cur.execute(f.read())

            with test_data.open() as f:
                cur.execute(f.read())
            conn.commit()
        
        # Yield the connection for use in tests
        yield conn
        
        # Connection closes automatically via context manager