-- ENABLE THE EXTENSION FIRST
CREATE EXTENSION IF NOT EXISTS vector;

-- 1. Create the base tables with Identity columns
CREATE TABLE books (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    publisher TEXT,
    publishedDate TEXT,
    description TEXT,
    pageCount INTEGER,
    printType TEXT,
    language TEXT,
    infoLink TEXT,
    smallThumbnail TEXT,
    isbn TEXT UNIQUE
);

CREATE TABLE authors (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT UNIQUE NOT NULL,
    birth_date TEXT,
    death_date TEXT,
    nationality TEXT,
    sex TEXT,
    bio TEXT,
    author_link TEXT
);

CREATE TABLE categories (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT UNIQUE NOT NULL
);

-- 2. Update Relationship tables to use INTEGER foreign keys
CREATE TABLE book_authors (
    book_id INTEGER REFERENCES books(id) ON DELETE CASCADE,
    author_id INTEGER REFERENCES authors(id) ON DELETE CASCADE,
    PRIMARY KEY (book_id, author_id)
);

CREATE TABLE book_categories (
    book_id INTEGER REFERENCES books(id) ON DELETE CASCADE,
    category_id INTEGER REFERENCES categories(id) ON DELETE CASCADE,
    PRIMARY KEY (book_id, category_id)
);

-- 3. Update Embedding tables
CREATE TABLE book_embeddings (
    book_id INTEGER REFERENCES books(id) ON DELETE CASCADE,
    model_name TEXT,
    vector VECTOR(1536), 
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (book_id, model_name)
);